import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
export const DEFAULT_MODEL_DIR = path.resolve(ROOT, '../mono-pix/src/assets/examples')
export const DEFAULT_DEMO_DIR = path.resolve(ROOT, 'examples')
export const DEFAULT_OUT_DIR = path.resolve(ROOT, '.tmp/snap-quality-eval')
export const MAX_METRIC_SAMPLES = 500_000

export const QUALITY_RULES = {
  maxAspectError: 0.03,
  maxShortAxisCells: 256,
  maxLongAxisCellsReview: 1024,
  minSourceCellSize: 3,
  maxSourceCellSizeReview: 64,
  maxRepeatGridGapFloor: 2,
  maxRepeatGridGapRate: 0.01,
  maxRepeatVisualMae: 0.5,
  maxRepeatVisualP95: 2,
  maxRepeatVisualAlphaMae: 0,
  maxRepeatVisualAlphaP95: 0,
  maxDeterminismVisualMae: 0,
  maxDeterminismVisualP95: 0,
  maxDeterminismVisualAlphaMae: 0,
  maxDeterminismVisualAlphaP95: 0,
  maxExpectedGridGap: 0,
  minEdgeAlignment: 0.6,
  minAxisEdgeAlignment: 0.35,
  minPhaseAlignment: 0.6,
  minAxisPhaseAlignment: 0.35,
  minCellColorDominance: 0.18,
  minCellColorDominanceP05: 0.05,
  minCellColorDominanceMin: 0.04,
  maxCellColorErrorMean: 30,
  maxCellColorErrorP95: 45,
  maxCellColorErrorP99: 70,
  maxCellColorErrorMaxReview: 240,
  maxCellAlphaErrorMean: 8,
  maxCellAlphaErrorP95: 24,
  maxCellAlphaErrorMaxReview: 240,
  minExactLowPaletteCellDominance: 0.999,
  maxExactLowPaletteCellColorErrorMax: 0.01,
  maxExactLowPaletteCellAlphaErrorMax: 0.01,
  minExactCellColorAdjacencyCount: 1,
  maxExactCellColorAdjacencyDrift: 0,
  minExactCellColorDiagonalAdjacencyCount: 1,
  maxExactCellColorDiagonalAdjacencyDrift: 0,
  minExactCellColorBoundaryPairCount: 1,
  maxExactCellColorBoundaryPairDrift: 0,
  minExactCellColorDiagonalBoundaryPairCount: 1,
  maxExactCellColorDiagonalBoundaryPairDrift: 0,
  minExactCellColorBoundaryRunCount: 1,
  maxExactCellColorBoundaryRunDrift: 0,
  minExactCellColorNeighborMaskCount: 1,
  maxExactCellColorNeighborMaskDrift: 0,
  minExactCellColorQuadPatternCount: 1,
  maxExactCellColorQuadPatternDrift: 0,
  minExactCellColorWindowPatternCount: 1,
  maxExactCellColorWindowPatternDrift: 0,
  minExactCellColorRunCount: 1,
  maxExactCellColorRunDrift: 0,
  minExactCellColorProjectionCount: 1,
  maxExactCellColorProjectionDrift: 0,
  minExactCellColorComponentCount: 2,
  maxExactCellColorComponentCountDrift: 0,
  maxExactCellColorComponentAreaDrift: 0,
  maxExactCellColorComponentBBoxDrift: 0,
  maxExactCellColorComponentHoleCountDrift: 0,
  maxExactCellColorComponentPerimeterDrift: 0,
  maxExactCellColorComponentPositionDrift: 0,
  minExactCellColorComponentHoleCount: 1,
  minExactSmallCellColorComponentCount: 1,
  maxExactSmallCellColorComponentCountDrift: 0,
  minCellTransitionCount: 24,
  minCellTransitionRetention: 0.7,
  maxCellTransitionSpuriousRatio: 0.45,
  maxCellTransitionErrorMean: 10,
  maxCellTransitionErrorP95: 36,
  maxCellTransitionErrorP99: 59.5,
  minCellDiagonalTransitionCount: 24,
  minCellDiagonalTransitionRetention: 0.7,
  maxCellDiagonalTransitionSpuriousRatio: 0.45,
  maxCellDiagonalTransitionErrorMean: 10,
  maxCellDiagonalTransitionErrorP95: 36,
  maxCellDiagonalTransitionErrorP99: 59.5,
  highCellMae: 18,
  highCellStdDev: 30,
  maxPreservationMae: 38,
  maxPreservationP95: 70,
  maxTilePreservationMae: 40,
  maxTilePreservationP95: 28,
  minChromaMeanForRatio: 8,
  minChromaRatio: 0.9,
  maxChromaRatio: 1.2,
  minHueSampleCount: 1000,
  maxHueErrorMean: 25,
  maxHueErrorP95: 80,
  maxAlphaMae: 8,
  maxAlphaP95: 40,
  maxAlphaMax: 0,
  maxAlphaTileMae: 40,
  maxAlphaTileP95: 20,
  minAlphaCoverageRatio: 0.98,
  maxAlphaCoverageRatio: 1.02,
  minAlphaMaskIou: 0.98,
  maxAlphaBBoxDriftRatio: 0.01,
  minAlphaComponentCount: 2,
  maxAlphaComponentCountDrift: 0,
  maxAlphaComponentAreaDrift: 0,
  maxAlphaComponentBBoxDrift: 0,
  maxAlphaComponentPerimeterDrift: 0,
  maxAlphaComponentPositionDrift: 0,
  maxAlphaHoleCountDrift: 0,
  minAlphaHoleCount: 1,
  minAlphaSmallComponentCount: 1,
  maxAlphaSmallComponentCountDrift: 0,
  minAlphaSemitransparentPixelCount: 16,
  minAlphaSemitransparentRetention: 0.95,
  maxAlphaSemitransparentValueMae: 8,
  maxAlphaSemitransparentValueP95: 16,
  maxAlphaSemitransparentSpuriousRatio: 0.1,
  minAlphaEdgeCount: 64,
  minAlphaEdgeRecall: 0.9,
  maxAlphaEdgeSpuriousRatio: 0.1,
  minAlphaEdgeJaccard: 0.85,
  maxOutputCellMae: 0.01,
  maxOutputAlphaCellMae: 0.01,
  maxOutputSquareCellError: 0.001,
  maxOutputCellIntegerError: 0.001,
  maxOutputRgbPaletteOverage: 0,
  maxOutputColorDominance: 0.65,
  maxPaletteDominanceDelta: 0.2,
  minPaletteUtilizationTarget: 16,
  minOutputPaletteUtilization: 0.5,
  maxPaletteUtilizationGap: 8,
  minLowPaletteRetention: 0.95,
  maxLowPaletteGrowth: 1,
  maxLowPaletteCoverageDrift: 0.03,
  minLowPaletteCoverageRetention: 0.97,
  minLowPaletteTileCoverageCount: 1,
  maxLowPaletteTileCoverageDrift: 0.95,
  minLowPaletteTileCoverageRetention: 0.05,
  minOutputCoverage: 0.9,
  minOutputAreaCoverage: 0.85,
  maxOutputExpansion: 1.05,
  minContrastRatio: 0.45,
  maxContrastRatio: 1.8,
  minLineEdgeRatio: 0.55,
  maxLineEdgeRatio: 2.4,
  minEdgeDirectionCount: 64,
  maxEdgeDirectionDrift: 0.7,
  minEdgeRecall: 0.88,
  maxEdgeSpuriousRatio: 0.38,
  minEdgeJaccard: 0.5,
  minEdgeTileCount: 1,
  minEdgeTileJaccard: 0.35,
  minEdgeTileRecall: 0.7,
  maxEdgeTileSpuriousRatio: 0.5,
}

export const KNOWN_EXPECTATIONS = [
  ['demo-examples/example-32-clean.png', { cols: 32, rows: 32 }],
  ['demo-examples/example-32-detail.png', { cols: 32, rows: 32 }],
  ['demo-examples/example-64-clean.png', { cols: 64, rows: 64 }],
  ['demo-examples/example-64-detail.png', { cols: 64, rows: 64 }],
]

export function defaultDatasets() {
  return [
    { name: 'model-examples', dir: DEFAULT_MODEL_DIR },
    { name: 'demo-examples', dir: DEFAULT_DEMO_DIR },
  ]
}
