import { QUALITY_RULES } from './config.mjs'
import { formatNum } from './classify.mjs'

export function mean(results, key) {
  if (results.length === 0) return 0
  return formatNum(results.reduce((sum, item) => sum + item[key], 0) / results.length)
}

export function summarize(results) {
  const statusCounts = results.reduce((counts, item) => {
    counts[item.status] = (counts[item.status] ?? 0) + 1
    return counts
  }, {})

  return {
    count: results.length,
    statusCounts,
    objectiveMean: mean(results, 'objective'),
    repeatGridGapTotal: results.reduce((sum, item) => sum + item.repeatGridGap, 0),
    repeatVisualMaeMean: mean(results, 'repeatVisualMae'),
    repeatVisualP95Mean: mean(results, 'repeatVisualP95'),
    determinismVisualMaeMean: mean(results, 'determinismVisualMae'),
    determinismVisualP95Mean: mean(results, 'determinismVisualP95'),
    expectedGridGapTotal: results.reduce((sum, item) => sum + item.expectedGridGap, 0),
    preservationMaeMean: mean(results, 'preservationMae'),
    preservationP95Mean: mean(results, 'preservationP95'),
    tilePreservationMaxMaeMean: mean(results, 'tilePreservationMaxMae'),
    tilePreservationP95MaeMean: mean(results, 'tilePreservationP95Mae'),
    alphaMaeMean: mean(results, 'alphaMae'),
    alphaTileMaxMaeMean: mean(results, 'alphaTileMaxMae'),
    alphaTileP95MaeMean: mean(results, 'alphaTileP95Mae'),
    alphaCoverageRatioMean: mean(results, 'alphaCoverageRatio'),
    alphaMaskIouMean: mean(results, 'alphaMaskIou'),
    alphaBBoxDriftRatioMean: mean(results, 'alphaBBoxDriftRatio'),
    alphaComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentCountDrift,
      0,
    ),
    alphaComponentAreaDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentAreaDrift,
      0,
    ),
    alphaComponentBBoxDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentBBoxDrift,
      0,
    ),
    alphaComponentPerimeterDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentPerimeterDrift,
      0,
    ),
    alphaComponentPositionDriftMean: mean(results, 'alphaComponentPositionDrift'),
    alphaHoleCountDriftTotal: results.reduce((sum, item) => sum + item.alphaHoleCountDrift, 0),
    alphaSmallComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaSmallComponentCountDrift,
      0,
    ),
    alphaSemitransparentPixelCountTotal: results.reduce(
      (sum, item) => sum + item.alphaSemitransparentPixelCount,
      0,
    ),
    outputAlphaSemitransparentPixelCountTotal: results.reduce(
      (sum, item) => sum + item.outputAlphaSemitransparentPixelCount,
      0,
    ),
    alphaSemitransparentRetentionMean: mean(results, 'alphaSemitransparentRetention'),
    alphaSemitransparentSpuriousRatioMean: mean(results, 'alphaSemitransparentSpuriousRatio'),
    alphaSemitransparentValueMaeMean: mean(results, 'alphaSemitransparentValueMae'),
    alphaSemitransparentValueP95Mean: mean(results, 'alphaSemitransparentValueP95'),
    alphaEdgeRecallMean: mean(results, 'alphaEdgeRecall'),
    alphaEdgeSpuriousRatioMean: mean(results, 'alphaEdgeSpuriousRatio'),
    alphaEdgeJaccardMean: mean(results, 'alphaEdgeJaccard'),
    chromaRatioMean: mean(results, 'chromaRatio'),
    lowPaletteCoverageDriftMean: mean(results, 'lowPaletteCoverageDrift'),
    lowPaletteCoverageRetentionMean: mean(results, 'lowPaletteCoverageRetention'),
    hueErrorMean: mean(results, 'hueErrorMean'),
    hueErrorP95Mean: mean(results, 'hueErrorP95'),
    outputColorDominanceMean: mean(results, 'outputColorDominance'),
    paletteDominanceDeltaMean: mean(results, 'paletteDominanceDelta'),
    outputPaletteUtilizationMean: mean(results, 'outputPaletteUtilization'),
    outputCellMaeMean: mean(results, 'outputCellMae'),
    cellColorDominanceMean: mean(results, 'cellColorDominance'),
    cellColorDominanceP05Mean: mean(results, 'cellColorDominanceP05'),
    exactLowPaletteCellColorEligibleCount: results.filter(
      (item) => item.exactLowPaletteCellColorEligible,
    ).length,
    cellColorComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentCountDrift,
      0,
    ),
    cellColorComponentAreaDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentAreaDrift,
      0,
    ),
    cellColorComponentBBoxDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentBBoxDrift,
      0,
    ),
    cellColorComponentHoleCountDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentHoleCountDrift,
      0,
    ),
    cellColorComponentPerimeterDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentPerimeterDrift,
      0,
    ),
    cellColorComponentPositionDriftMean: mean(results, 'cellColorComponentPositionDrift'),
    smallCellColorComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.smallCellColorComponentCountDrift,
      0,
    ),
    cellColorErrorMean: mean(results, 'cellColorErrorMean'),
    cellColorErrorP95Mean: mean(results, 'cellColorErrorP95'),
    cellAlphaErrorMean: mean(results, 'cellAlphaErrorMean'),
    cellAlphaErrorP95Mean: mean(results, 'cellAlphaErrorP95'),
    cellTransitionRetentionMean: mean(results, 'cellTransitionRetention'),
    cellTransitionSpuriousRatioMean: mean(results, 'cellTransitionSpuriousRatio'),
    cellTransitionErrorMean: mean(results, 'cellTransitionErrorMean'),
    cellDiagonalTransitionRetentionMean: mean(results, 'cellDiagonalTransitionRetention'),
    cellDiagonalTransitionSpuriousRatioMean: mean(results, 'cellDiagonalTransitionSpuriousRatio'),
    cellDiagonalTransitionErrorMean: mean(results, 'cellDiagonalTransitionErrorMean'),
    cellDiagonalTransitionDirectionRetentionMinMean: mean(
      results,
      'cellDiagonalTransitionDirectionRetentionMin',
    ),
    cellDiagonalTransitionDirectionSpuriousRatioMaxMean: mean(
      results,
      'cellDiagonalTransitionDirectionSpuriousRatioMax',
    ),
    cellTransitionAxisRetentionMinMean: mean(results, 'cellTransitionAxisRetentionMin'),
    cellTransitionAxisSpuriousRatioMaxMean: mean(results, 'cellTransitionAxisSpuriousRatioMax'),
    edgeRecallMean: mean(results, 'edgeRecall'),
    edgeSpuriousRatioMean: mean(results, 'edgeSpuriousRatio'),
    edgeJaccardMean: mean(results, 'edgeJaccard'),
    outputAlphaCellMaeMean: mean(results, 'outputAlphaCellMae'),
    phaseAlignmentMean: mean(results, 'phaseAlignment'),
    axisPhaseAlignmentMinMean: mean(results, 'axisPhaseAlignmentMin'),
    lowPaletteRetentionMean: mean(results, 'lowPaletteRetention'),
    outputCoverageMean: mean(results, 'outputCoverage'),
    lineEdgeRatioMean: mean(results, 'lineEdgeRatio'),
    sourceCellSizeMean: mean(results, 'sourceCellSize'),
  }
}

export function summarizeByDataset(results) {
  const groups = new Map()
  for (const item of results) {
    groups.set(item.dataset, [...(groups.get(item.dataset) ?? []), item])
  }
  return Object.fromEntries([...groups].map(([dataset, items]) => [dataset, summarize(items)]))
}

function criteriaMarkdown() {
  return [
    '## Criteria',
    '',
    `- Ground truth: fail when synthetic expected-grid gap is greater than ${QUALITY_RULES.maxExpectedGridGap}.`,
    `- Aspect preservation: fail when grid aspect differs from source by more than ${QUALITY_RULES.maxAspectError}.`,
    `- No micro-grid snap: fail when the detected short axis exceeds ${QUALITY_RULES.maxShortAxisCells} cells or source cell size drops below ${QUALITY_RULES.minSourceCellSize}px.`,
    `- No macro-grid under-detection: review when source cell size exceeds ${QUALITY_RULES.maxSourceCellSizeReview}px.`,
    `- Idempotence: fail when snapping the snapped output changes the grid by more than max(${QUALITY_RULES.maxRepeatGridGapFloor}, ${(QUALITY_RULES.maxRepeatGridGapRate * 100).toFixed(1)}% of cols+rows).`,
    `- Visual idempotence: fail when re-snapping the snapped output changes pixels by MAE > ${QUALITY_RULES.maxRepeatVisualMae} or p95 > ${QUALITY_RULES.maxRepeatVisualP95}.`,
    `- Deep stability: fail when a second re-snap changes the grid at all.`,
    `- Determinism: fail when two snaps of the same source disagree on grid size.`,
    `- Visual determinism: fail when two snaps of the same source produce different original-size pixels.`,
    `- Output purity: fail when snapped output RGB cells are not single-color, alpha cells are not single-alpha, or cells are not square.`,
    `- Palette budget: fail when snapped RGB colors exceed colorVariety plus transparency allowance by more than ${QUALITY_RULES.maxOutputRgbPaletteOverage}.`,
    `- Palette dominance: review when one output color covers more than ${(QUALITY_RULES.maxOutputColorDominance * 100).toFixed(0)}% of visible cells and exceeds source bucket dominance by more than ${(QUALITY_RULES.maxPaletteDominanceDelta * 100).toFixed(0)} points.`,
    `- Palette utilization: review when a source with at least ${QUALITY_RULES.minPaletteUtilizationTarget} bucketed colors uses less than ${(QUALITY_RULES.minOutputPaletteUtilization * 100).toFixed(0)}% of the available snapped palette.`,
    `- Low-palette retention: review when limited-palette inputs keep less than ${(QUALITY_RULES.minLowPaletteRetention * 100).toFixed(0)}% of their RGB colors.`,
    `- Low-palette coverage: review when limited-palette inputs move visible RGB coverage by more than ${(QUALITY_RULES.maxLowPaletteCoverageDrift * 100).toFixed(0)}% or retain less than ${(QUALITY_RULES.minLowPaletteCoverageRetention * 100).toFixed(0)}% of source RGB coverage.`,
    `- Output coverage: review when original-size snap output keeps less than ${(QUALITY_RULES.minOutputCoverage * 100).toFixed(0)}% of the input canvas on either axis.`,
    `- Boundary evidence: review when inferred grid boundaries are weaker than ${QUALITY_RULES.minEdgeAlignment}x the average axis gradient.`,
    `- Axis boundary evidence: review when either axis is weaker than ${QUALITY_RULES.minAxisEdgeAlignment}x the average axis gradient.`,
    `- Phase alignment: review when inferred grid boundaries score below ${QUALITY_RULES.minPhaseAlignment} against nearby gradient peaks.`,
    `- Axis phase alignment: review when either axis scores below ${QUALITY_RULES.minAxisPhaseAlignment} against nearby gradient peaks.`,
    `- Cell color dominance: review when the average bucketed majority color share per inferred cell is below ${QUALITY_RULES.minCellColorDominance}.`,
    `- Cell representative color: review when snapped grid-cell color differs from source cell average by mean > ${QUALITY_RULES.maxCellColorErrorMean} or p95 > ${QUALITY_RULES.maxCellColorErrorP95}.`,
    `- Cell representative alpha: review when snapped grid-cell alpha differs from source cell average by mean > ${QUALITY_RULES.maxCellAlphaErrorMean} or p95 > ${QUALITY_RULES.maxCellAlphaErrorP95}.`,
    `- Rare exact-palette cell color: review when exact low-palette inputs with cell dominance at least ${QUALITY_RULES.minExactLowPaletteCellDominance} have any grid-cell color error above ${QUALITY_RULES.maxExactLowPaletteCellColorErrorMax}.`,
    `- Rare exact-palette cell alpha: review when exact low-palette inputs with cell dominance at least ${QUALITY_RULES.minExactLowPaletteCellDominance} have any grid-cell alpha error above ${QUALITY_RULES.maxExactLowPaletteCellAlphaErrorMax}.`,
    `- Exact cell color components: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorComponentCount} color components change component count, area, bounds, holes, perimeter, or position between source cells and output grid, or when at least ${QUALITY_RULES.minExactSmallCellColorComponentCount} small color component changes count.`,
    `- Cell transitions: review when at least ${QUALITY_RULES.minCellTransitionCount} source cell-adjacency transitions retain less than ${(QUALITY_RULES.minCellTransitionRetention * 100).toFixed(0)}% of their strength, or when output-only transitions exceed ${(QUALITY_RULES.maxCellTransitionSpuriousRatio * 100).toFixed(0)}% of output transition strength.`,
    `- Axis cell transitions: review when either horizontal or vertical cell-adjacency transitions breach the same cell transition limits.`,
    `- Diagonal cell transitions: review when at least ${QUALITY_RULES.minCellDiagonalTransitionCount} source diagonal cell-adjacency transitions retain less than ${(QUALITY_RULES.minCellDiagonalTransitionRetention * 100).toFixed(0)}% of their strength, or when output-only diagonal transitions exceed ${(QUALITY_RULES.maxCellDiagonalTransitionSpuriousRatio * 100).toFixed(0)}% of output diagonal transition strength.`,
    `- Directional diagonal cell transitions: review when either diagonal direction breaches the same diagonal transition limits.`,
    `- Source disorder: review when intra-cell source MAE exceeds ${QUALITY_RULES.highCellMae}.`,
    `- Preservation: review when average MAE exceeds ${QUALITY_RULES.maxPreservationMae} or p95 exceeds ${QUALITY_RULES.maxPreservationP95}.`,
    `- Regional preservation: review when any 8x8 canvas tile exceeds MAE ${QUALITY_RULES.maxTilePreservationMae} or tile p95 exceeds ${QUALITY_RULES.maxTilePreservationP95}.`,
    `- Alpha preservation: review when alpha MAE exceeds ${QUALITY_RULES.maxAlphaMae} or p95 exceeds ${QUALITY_RULES.maxAlphaP95}.`,
    `- Regional alpha preservation: review when any 8x8 canvas tile alpha MAE exceeds ${QUALITY_RULES.maxAlphaTileMae} or alpha tile p95 exceeds ${QUALITY_RULES.maxAlphaTileP95}.`,
    `- Alpha silhouette: review when visible alpha coverage falls outside ${QUALITY_RULES.minAlphaCoverageRatio}-${QUALITY_RULES.maxAlphaCoverageRatio}, mask IoU drops below ${QUALITY_RULES.minAlphaMaskIou}, or visible bounds drift more than ${(QUALITY_RULES.maxAlphaBBoxDriftRatio * 100).toFixed(1)}% of the canvas.`,
    `- Alpha components: review when at least ${QUALITY_RULES.minAlphaComponentCount} visible alpha components change count, area, bounds, perimeter, or position between source and output, when at least ${QUALITY_RULES.minAlphaHoleCount} alpha hole changes count, or when at least ${QUALITY_RULES.minAlphaSmallComponentCount} small alpha component changes count.`,
    `- Alpha semitransparency: review when at least ${QUALITY_RULES.minAlphaSemitransparentPixelCount} source semitransparent pixels retain less than ${(QUALITY_RULES.minAlphaSemitransparentRetention * 100).toFixed(0)}%, source semitransparent alpha value MAE exceeds ${QUALITY_RULES.maxAlphaSemitransparentValueMae} or p95 exceeds ${QUALITY_RULES.maxAlphaSemitransparentValueP95}, or at least ${QUALITY_RULES.minAlphaSemitransparentPixelCount} output semitransparent pixels are more than ${(QUALITY_RULES.maxAlphaSemitransparentSpuriousRatio * 100).toFixed(0)}% output-only.`,
    `- Alpha edge map: review when at least ${QUALITY_RULES.minAlphaEdgeCount} source alpha edges retain less than ${(QUALITY_RULES.minAlphaEdgeRecall * 100).toFixed(0)}%, overlap drops below ${QUALITY_RULES.minAlphaEdgeJaccard}, or output-only alpha edges exceed ${(QUALITY_RULES.maxAlphaEdgeSpuriousRatio * 100).toFixed(0)}%.`,
    `- Contrast: review when snapped contrast ratio falls outside ${QUALITY_RULES.minContrastRatio}-${QUALITY_RULES.maxContrastRatio}.`,
    `- Chroma: review when colorful inputs with mean chroma at least ${QUALITY_RULES.minChromaMeanForRatio} fall outside chroma ratio ${QUALITY_RULES.minChromaRatio}-${QUALITY_RULES.maxChromaRatio}.`,
    `- Hue: review when at least ${QUALITY_RULES.minHueSampleCount} colorful pixels have hue error mean > ${QUALITY_RULES.maxHueErrorMean} degrees or p95 > ${QUALITY_RULES.maxHueErrorP95} degrees.`,
    `- Line strength: review when resized snap edge strength falls outside ${QUALITY_RULES.minLineEdgeRatio}-${QUALITY_RULES.maxLineEdgeRatio}x the source edge strength.`,
    `- Edge map overlap: review when fewer than ${(QUALITY_RULES.minEdgeRecall * 100).toFixed(0)}% of strong source edges survive nearby, when more than ${(QUALITY_RULES.maxEdgeSpuriousRatio * 100).toFixed(0)}% of strong output edges are not near source edges, or when tolerant edge overlap drops below ${QUALITY_RULES.minEdgeJaccard}.`,
    '',
  ]
}

export function toMarkdown(summary) {
  const headers = [
    'dataset',
    'file',
    'input',
    'output',
    'outputCoverage',
    'grid',
    'expectedGrid',
    'sourceCellSize',
    'aspectError',
    'edgeAlignment',
    'axisEdgeAlignmentMin',
    'phaseAlignment',
    'axisPhaseAlignmentMin',
    'cellColorDominance',
    'cellColorDominanceP05',
    'exactLowPaletteCellColorEligible',
    'sourceCellColorComponentCount',
    'outputCellColorComponentCount',
    'sourceCellColorComponentHoleCount',
    'outputCellColorComponentHoleCount',
    'cellColorComponentCountDrift',
    'cellColorComponentAreaDrift',
    'cellColorComponentBBoxDrift',
    'cellColorComponentHoleCountDrift',
    'cellColorComponentPerimeterDrift',
    'cellColorComponentPositionDrift',
    'sourceSmallCellColorComponentCount',
    'outputSmallCellColorComponentCount',
    'smallCellColorComponentCountDrift',
    'cellAlphaErrorMean',
    'cellAlphaErrorP95',
    'cellAlphaErrorMax',
    'cellColorErrorMean',
    'cellColorErrorP95',
    'cellColorErrorMax',
    'cellTransitionRetention',
    'cellTransitionSpuriousRatio',
    'cellTransitionErrorMean',
    'cellDiagonalTransitionRetention',
    'cellDiagonalTransitionSpuriousRatio',
    'cellDiagonalTransitionErrorMean',
    'cellDiagonalTransitionDirectionRetentionMin',
    'cellDiagonalTransitionDirectionSpuriousRatioMax',
    'cellDiagonalTransitionDownRightRetention',
    'cellDiagonalTransitionDownLeftRetention',
    'cellDiagonalTransitionDownRightSpuriousRatio',
    'cellDiagonalTransitionDownLeftSpuriousRatio',
    'cellTransitionAxisRetentionMin',
    'cellTransitionAxisSpuriousRatioMax',
    'cellTransitionXRetention',
    'cellTransitionYRetention',
    'cellTransitionXSpuriousRatio',
    'cellTransitionYSpuriousRatio',
    'sourceCellTransitionCount',
    'sourceCellTransitionXCount',
    'sourceCellTransitionYCount',
    'sourceCellDiagonalTransitionCount',
    'sourceCellDiagonalTransitionDownRightCount',
    'sourceCellDiagonalTransitionDownLeftCount',
    'outputCellTransitionCount',
    'outputCellTransitionXCount',
    'outputCellTransitionYCount',
    'outputCellDiagonalTransitionCount',
    'outputCellDiagonalTransitionDownRightCount',
    'outputCellDiagonalTransitionDownLeftCount',
    'cellMae',
    'outputCellMae',
    'outputAlphaCellMae',
    'preservationMae',
    'preservationP95',
    'tilePreservationMaxMae',
    'tilePreservationP95Mae',
    'alphaMae',
    'alphaP95',
    'alphaTileMaxMae',
    'alphaTileP95Mae',
    'alphaCoverageRatio',
    'alphaMaskIou',
    'alphaBBoxDriftPx',
    'alphaBBoxDriftRatio',
    'alphaComponentCount',
    'outputAlphaComponentCount',
    'alphaComponentCountDrift',
    'alphaComponentAreaDrift',
    'alphaComponentBBoxDrift',
    'alphaComponentPerimeterDrift',
    'alphaComponentPositionDrift',
    'alphaHoleCount',
    'outputAlphaHoleCount',
    'alphaHoleCountDrift',
    'alphaSmallComponentCount',
    'outputAlphaSmallComponentCount',
    'alphaSmallComponentCountDrift',
    'alphaSemitransparentPixelCount',
    'outputAlphaSemitransparentPixelCount',
    'alphaSemitransparentRetention',
    'alphaSemitransparentSpuriousRatio',
    'alphaSemitransparentValueMae',
    'alphaSemitransparentValueP95',
    'alphaEdgeCount',
    'outputAlphaEdgeCount',
    'alphaEdgeRecall',
    'alphaEdgeSpuriousRatio',
    'alphaEdgeJaccard',
    'inputChromaMean',
    'outputChromaMean',
    'chromaRatio',
    'lowPaletteCoverageDrift',
    'lowPaletteCoverageRetention',
    'lowPaletteCoverageEligible',
    'hueErrorMean',
    'hueErrorP95',
    'hueSampleCount',
    'contrastRatio',
    'lineEdgeRatio',
    'edgeRecall',
    'edgeSpuriousRatio',
    'edgeJaccard',
    'repeatGridGap',
    'repeatVisualMae',
    'repeatVisualP95',
    'determinismVisualMae',
    'determinismVisualP95',
    'expectedGridGap',
    'inputRgbColorCount',
    'inputBucketColorCount',
    'inputColorDominance',
    'outputRgbColorCount',
    'outputPaletteColorCount',
    'outputPaletteUtilization',
    'paletteUtilizationGap',
    'paletteUtilizationTarget',
    'outputColorDominance',
    'paletteDominanceDelta',
    'outputRgbPaletteOverage',
    'lowPaletteRetention',
    'status',
    'issueSummary',
    'objective',
  ]
  const lines = [
    '# Snap Quality Eval',
    '',
    `Color variety: \`${summary.colorVariety}\``,
    '',
    ...criteriaMarkdown(),
    '## Datasets',
    '',
    ...summary.datasets.map((dataset) => `- \`${dataset.name}\`: \`${dataset.dir}\``),
    '',
    '## Aggregate',
    '',
    '```json',
    JSON.stringify(summary.aggregate, null, 2),
    '```',
    '',
    '## Results',
    '',
    '| ' + headers.join(' | ') + ' |',
    '| ' + headers.map(() => '---').join(' | ') + ' |',
  ]

  for (const result of summary.results) {
    lines.push('| ' + headers.map((header) => String(result[header])).join(' | ') + ' |')
  }

  return `${lines.join('\n')}\n`
}
