import { QUALITY_RULES } from './config.mjs'
import { formatNum } from './classify.mjs'

export function mean(results, key) {
  if (results.length === 0) return 0
  return formatNum(results.reduce((sum, item) => sum + item[key], 0) / results.length)
}

export function summarize(results) {
  const statusCounts = results.reduce((counts, item) => {
    counts[item.status] = (counts[item.status] ?? 0) + 1
    return counts
  }, {})

  return {
    count: results.length,
    statusCounts,
    objectiveMean: mean(results, 'objective'),
    repeatGridGapTotal: results.reduce((sum, item) => sum + item.repeatGridGap, 0),
    repeatVisualMaeMean: mean(results, 'repeatVisualMae'),
    repeatVisualP95Mean: mean(results, 'repeatVisualP95'),
    repeatVisualAlphaMaeMean: mean(results, 'repeatVisualAlphaMae'),
    repeatVisualAlphaP95Mean: mean(results, 'repeatVisualAlphaP95'),
    determinismVisualMaeMean: mean(results, 'determinismVisualMae'),
    determinismVisualP95Mean: mean(results, 'determinismVisualP95'),
    determinismVisualAlphaMaeMean: mean(results, 'determinismVisualAlphaMae'),
    determinismVisualAlphaP95Mean: mean(results, 'determinismVisualAlphaP95'),
    expectedGridGapTotal: results.reduce((sum, item) => sum + item.expectedGridGap, 0),
    preservationMaeMean: mean(results, 'preservationMae'),
    preservationP95Mean: mean(results, 'preservationP95'),
    tilePreservationMaxMaeMean: mean(results, 'tilePreservationMaxMae'),
    tilePreservationP95MaeMean: mean(results, 'tilePreservationP95Mae'),
    alphaMaeMean: mean(results, 'alphaMae'),
    alphaTileMaxMaeMean: mean(results, 'alphaTileMaxMae'),
    alphaTileP95MaeMean: mean(results, 'alphaTileP95Mae'),
    alphaCoverageRatioMean: mean(results, 'alphaCoverageRatio'),
    alphaMaskIouMean: mean(results, 'alphaMaskIou'),
    alphaBBoxDriftRatioMean: mean(results, 'alphaBBoxDriftRatio'),
    alphaComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentCountDrift,
      0,
    ),
    alphaComponentAreaDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentAreaDrift,
      0,
    ),
    alphaComponentBBoxDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentBBoxDrift,
      0,
    ),
    alphaComponentPerimeterDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaComponentPerimeterDrift,
      0,
    ),
    alphaComponentPositionDriftMean: mean(results, 'alphaComponentPositionDrift'),
    alphaHoleCountDriftTotal: results.reduce((sum, item) => sum + item.alphaHoleCountDrift, 0),
    alphaSmallComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.alphaSmallComponentCountDrift,
      0,
    ),
    alphaSemitransparentPixelCountTotal: results.reduce(
      (sum, item) => sum + item.alphaSemitransparentPixelCount,
      0,
    ),
    outputAlphaSemitransparentPixelCountTotal: results.reduce(
      (sum, item) => sum + item.outputAlphaSemitransparentPixelCount,
      0,
    ),
    alphaSemitransparentRetentionMean: mean(results, 'alphaSemitransparentRetention'),
    alphaSemitransparentSpuriousRatioMean: mean(results, 'alphaSemitransparentSpuriousRatio'),
    alphaSemitransparentValueMaeMean: mean(results, 'alphaSemitransparentValueMae'),
    alphaSemitransparentValueP95Mean: mean(results, 'alphaSemitransparentValueP95'),
    alphaEdgeRecallMean: mean(results, 'alphaEdgeRecall'),
    alphaEdgeSpuriousRatioMean: mean(results, 'alphaEdgeSpuriousRatio'),
    alphaEdgeJaccardMean: mean(results, 'alphaEdgeJaccard'),
    chromaRatioMean: mean(results, 'chromaRatio'),
    lowPaletteCoverageDriftMean: mean(results, 'lowPaletteCoverageDrift'),
    lowPaletteCoverageRetentionMean: mean(results, 'lowPaletteCoverageRetention'),
    lowPaletteTileCoverageDriftMax: results.reduce(
      (max, item) => Math.max(max, item.lowPaletteTileCoverageDriftMax),
      0,
    ),
    lowPaletteTileCoverageRetentionMin: results.reduce(
      (min, item) => Math.min(min, item.lowPaletteTileCoverageRetentionMin),
      results.length > 0 ? 1 : 0,
    ),
    lowPaletteTileCoverageTileCountTotal: results.reduce(
      (sum, item) => sum + item.lowPaletteTileCoverageTileCount,
      0,
    ),
    hueErrorMean: mean(results, 'hueErrorMean'),
    hueErrorP95Mean: mean(results, 'hueErrorP95'),
    outputColorDominanceMean: mean(results, 'outputColorDominance'),
    paletteDominanceDeltaMean: mean(results, 'paletteDominanceDelta'),
    outputPaletteUtilizationMean: mean(results, 'outputPaletteUtilization'),
    outputCellMaeMean: mean(results, 'outputCellMae'),
    cellColorDominanceMean: mean(results, 'cellColorDominance'),
    cellColorDominanceP05Mean: mean(results, 'cellColorDominanceP05'),
    exactLowPaletteCellColorEligibleCount: results.filter(
      (item) => item.exactLowPaletteCellColorEligible,
    ).length,
    cellColorAdjacencyDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorAdjacencyDrift,
      0,
    ),
    cellColorDiagonalAdjacencyDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorDiagonalAdjacencyDrift,
      0,
    ),
    cellColorBoundaryPairDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorBoundaryPairDrift,
      0,
    ),
    cellColorDiagonalBoundaryPairDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorDiagonalBoundaryPairDrift,
      0,
    ),
    cellColorBoundaryHorizontalRunDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorBoundaryHorizontalRunDrift,
      0,
    ),
    cellColorBoundaryVerticalRunDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorBoundaryVerticalRunDrift,
      0,
    ),
    cellColorNeighborMaskDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorNeighborMaskDrift,
      0,
    ),
    cellColorQuadPatternDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorQuadPatternDrift,
      0,
    ),
    cellColorWindowPatternDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorWindowPatternDrift,
      0,
    ),
    cellColorHorizontalRunDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorHorizontalRunDrift,
      0,
    ),
    cellColorVerticalRunDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorVerticalRunDrift,
      0,
    ),
    cellColorRowProjectionDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorRowProjectionDrift,
      0,
    ),
    cellColorColumnProjectionDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorColumnProjectionDrift,
      0,
    ),
    cellColorComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentCountDrift,
      0,
    ),
    cellColorComponentAreaDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentAreaDrift,
      0,
    ),
    cellColorComponentBBoxDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentBBoxDrift,
      0,
    ),
    cellColorComponentHoleCountDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentHoleCountDrift,
      0,
    ),
    cellColorComponentPerimeterDriftTotal: results.reduce(
      (sum, item) => sum + item.cellColorComponentPerimeterDrift,
      0,
    ),
    cellColorComponentPositionDriftMean: mean(results, 'cellColorComponentPositionDrift'),
    smallCellColorComponentCountDriftTotal: results.reduce(
      (sum, item) => sum + item.smallCellColorComponentCountDrift,
      0,
    ),
    cellColorErrorMean: mean(results, 'cellColorErrorMean'),
    cellColorErrorP95Mean: mean(results, 'cellColorErrorP95'),
    cellAlphaErrorMean: mean(results, 'cellAlphaErrorMean'),
    cellAlphaErrorP95Mean: mean(results, 'cellAlphaErrorP95'),
    cellTransitionRetentionMean: mean(results, 'cellTransitionRetention'),
    cellTransitionSpuriousRatioMean: mean(results, 'cellTransitionSpuriousRatio'),
    cellTransitionErrorMean: mean(results, 'cellTransitionErrorMean'),
    cellDiagonalTransitionRetentionMean: mean(results, 'cellDiagonalTransitionRetention'),
    cellDiagonalTransitionSpuriousRatioMean: mean(results, 'cellDiagonalTransitionSpuriousRatio'),
    cellDiagonalTransitionErrorMean: mean(results, 'cellDiagonalTransitionErrorMean'),
    cellDiagonalTransitionDirectionRetentionMinMean: mean(
      results,
      'cellDiagonalTransitionDirectionRetentionMin',
    ),
    cellDiagonalTransitionDirectionSpuriousRatioMaxMean: mean(
      results,
      'cellDiagonalTransitionDirectionSpuriousRatioMax',
    ),
    cellTransitionAxisRetentionMinMean: mean(results, 'cellTransitionAxisRetentionMin'),
    cellTransitionAxisSpuriousRatioMaxMean: mean(results, 'cellTransitionAxisSpuriousRatioMax'),
    edgeRecallMean: mean(results, 'edgeRecall'),
    edgeSpuriousRatioMean: mean(results, 'edgeSpuriousRatio'),
    edgeJaccardMean: mean(results, 'edgeJaccard'),
    edgeDirectionDriftMean: mean(results, 'edgeDirectionDrift'),
    sourceEdgeDirectionCountTotal: results.reduce(
      (sum, item) => sum + item.sourceEdgeDirectionCount,
      0,
    ),
    outputEdgeDirectionCountTotal: results.reduce(
      (sum, item) => sum + item.outputEdgeDirectionCount,
      0,
    ),
    edgeTileRecallMin: results.reduce(
      (min, item) => Math.min(min, item.edgeTileRecallMin),
      results.length > 0 ? 1 : 0,
    ),
    edgeTileSpuriousMax: results.reduce((max, item) => Math.max(max, item.edgeTileSpuriousMax), 0),
    sourceEdgeTileCountTotal: results.reduce((sum, item) => sum + item.sourceEdgeTileCount, 0),
    outputEdgeTileCountTotal: results.reduce((sum, item) => sum + item.outputEdgeTileCount, 0),
    outputAlphaCellMaeMean: mean(results, 'outputAlphaCellMae'),
    phaseAlignmentMean: mean(results, 'phaseAlignment'),
    axisPhaseAlignmentMinMean: mean(results, 'axisPhaseAlignmentMin'),
    lowPaletteRetentionMean: mean(results, 'lowPaletteRetention'),
    outputCoverageMean: mean(results, 'outputCoverage'),
    lineEdgeRatioMean: mean(results, 'lineEdgeRatio'),
    sourceCellSizeMean: mean(results, 'sourceCellSize'),
  }
}

export function summarizeByDataset(results) {
  const groups = new Map()
  for (const item of results) {
    groups.set(item.dataset, [...(groups.get(item.dataset) ?? []), item])
  }
  return Object.fromEntries([...groups].map(([dataset, items]) => [dataset, summarize(items)]))
}

function criteriaMarkdown() {
  return [
    '## Criteria',
    '',
    `- Ground truth: fail when synthetic expected-grid gap is greater than ${QUALITY_RULES.maxExpectedGridGap}.`,
    `- Aspect preservation: fail when grid aspect differs from source by more than ${QUALITY_RULES.maxAspectError}.`,
    `- No micro-grid snap: fail when the detected short axis exceeds ${QUALITY_RULES.maxShortAxisCells} cells or source cell size drops below ${QUALITY_RULES.minSourceCellSize}px.`,
    `- No macro-grid under-detection: review when source cell size exceeds ${QUALITY_RULES.maxSourceCellSizeReview}px.`,
    `- Idempotence: fail when snapping the snapped output changes the grid by more than max(${QUALITY_RULES.maxRepeatGridGapFloor}, ${(QUALITY_RULES.maxRepeatGridGapRate * 100).toFixed(1)}% of cols+rows).`,
    `- Visual idempotence: fail when re-snapping the snapped output changes pixels by MAE > ${QUALITY_RULES.maxRepeatVisualMae} or p95 > ${QUALITY_RULES.maxRepeatVisualP95}.`,
    `- Alpha idempotence: fail when re-snapping the snapped output changes alpha by MAE > ${QUALITY_RULES.maxRepeatVisualAlphaMae} or p95 > ${QUALITY_RULES.maxRepeatVisualAlphaP95}.`,
    `- Deep stability: fail when a second re-snap changes the grid at all.`,
    `- Determinism: fail when two snaps of the same source disagree on grid size.`,
    `- Visual determinism: fail when two snaps of the same source produce different original-size pixels.`,
    `- Alpha determinism: fail when two snaps of the same source produce different original-size alpha.`,
    `- Output purity: fail when snapped output RGB cells are not single-color, alpha cells are not single-alpha, or cells are not square.`,
    `- Palette budget: fail when snapped RGB colors exceed colorVariety plus transparency allowance by more than ${QUALITY_RULES.maxOutputRgbPaletteOverage}.`,
    `- Palette dominance: review when one output color covers more than ${(QUALITY_RULES.maxOutputColorDominance * 100).toFixed(0)}% of visible cells and exceeds source bucket dominance by more than ${(QUALITY_RULES.maxPaletteDominanceDelta * 100).toFixed(0)} points.`,
    `- Palette utilization: review when a source with at least ${QUALITY_RULES.minPaletteUtilizationTarget} bucketed colors uses less than ${(QUALITY_RULES.minOutputPaletteUtilization * 100).toFixed(0)}% of the available snapped palette.`,
    `- Low-palette retention: review when limited-palette inputs keep less than ${(QUALITY_RULES.minLowPaletteRetention * 100).toFixed(0)}% of their RGB colors.`,
    `- Low-palette coverage: review when limited-palette inputs move visible RGB coverage by more than ${(QUALITY_RULES.maxLowPaletteCoverageDrift * 100).toFixed(0)}% or retain less than ${(QUALITY_RULES.minLowPaletteCoverageRetention * 100).toFixed(0)}% of source RGB coverage.`,
    `- Regional low-palette coverage: review when any eligible canvas tile moves visible RGB coverage by more than ${(QUALITY_RULES.maxLowPaletteTileCoverageDrift * 100).toFixed(0)}% or retains less than ${(QUALITY_RULES.minLowPaletteTileCoverageRetention * 100).toFixed(0)}% of source RGB coverage.`,
    `- Output coverage: review when original-size snap output keeps less than ${(QUALITY_RULES.minOutputCoverage * 100).toFixed(0)}% of the input canvas on either axis.`,
    `- Boundary evidence: review when inferred grid boundaries are weaker than ${QUALITY_RULES.minEdgeAlignment}x the average axis gradient.`,
    `- Axis boundary evidence: review when either axis is weaker than ${QUALITY_RULES.minAxisEdgeAlignment}x the average axis gradient.`,
    `- Phase alignment: review when inferred grid boundaries score below ${QUALITY_RULES.minPhaseAlignment} against nearby gradient peaks.`,
    `- Axis phase alignment: review when either axis scores below ${QUALITY_RULES.minAxisPhaseAlignment} against nearby gradient peaks.`,
    `- Cell color dominance: review when the average bucketed majority color share per inferred cell is below ${QUALITY_RULES.minCellColorDominance}.`,
    `- Localized cell color dominance: review when the bottom 5% bucketed majority color share per inferred cell is below ${QUALITY_RULES.minCellColorDominanceP05}.`,
    `- Cell representative color: review when snapped grid-cell color differs from source cell average by mean > ${QUALITY_RULES.maxCellColorErrorMean} or p95 > ${QUALITY_RULES.maxCellColorErrorP95}.`,
    `- Cell representative alpha: review when snapped grid-cell alpha differs from source cell average by mean > ${QUALITY_RULES.maxCellAlphaErrorMean} or p95 > ${QUALITY_RULES.maxCellAlphaErrorP95}.`,
    `- Rare exact-palette cell color: review when exact low-palette inputs with cell dominance at least ${QUALITY_RULES.minExactLowPaletteCellDominance} have any grid-cell color error above ${QUALITY_RULES.maxExactLowPaletteCellColorErrorMax}.`,
    `- Rare exact-palette cell alpha: review when exact low-palette inputs with cell dominance at least ${QUALITY_RULES.minExactLowPaletteCellDominance} have any grid-cell alpha error above ${QUALITY_RULES.maxExactLowPaletteCellAlphaErrorMax}.`,
    `- Exact cell color adjacencies: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorAdjacencyCount} same-color orthogonal adjacency change count, or with at least ${QUALITY_RULES.minExactCellColorDiagonalAdjacencyCount} same-color diagonal adjacency change count.`,
    `- Exact cell color boundary pairs: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorBoundaryPairCount} different-color orthogonal boundary pair or at least ${QUALITY_RULES.minExactCellColorDiagonalBoundaryPairCount} diagonal boundary pair changes color-pair frequency.`,
    `- Exact cell color boundary runs: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorBoundaryRunCount} different-color horizontal or vertical boundary run changes color-pair length frequency.`,
    `- Exact cell color neighbor masks: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorNeighborMaskCount} visible color cell changes same-color N/E/S/W topology frequency.`,
    `- Exact cell color 2x2 patterns: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorQuadPatternCount} 2x2 cell pattern changes pattern frequency.`,
    `- Exact cell color 3x3 window patterns: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorWindowPatternCount} visible 3x3 neighborhood changes pattern frequency.`,
    `- Exact cell color runs: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorRunCount} same-color horizontal or vertical run changes length frequency.`,
    `- Exact cell color projections: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorProjectionCount} visible projected color cell changes row or column occupancy.`,
    `- Exact cell color components: review when exact low-palette inputs with at least ${QUALITY_RULES.minExactCellColorComponentCount} color components change component count, area, bounds, holes, perimeter, or position between source cells and output grid, or when at least ${QUALITY_RULES.minExactSmallCellColorComponentCount} small color component changes count.`,
    `- Cell transitions: review when at least ${QUALITY_RULES.minCellTransitionCount} source cell-adjacency transitions retain less than ${(QUALITY_RULES.minCellTransitionRetention * 100).toFixed(0)}% of their strength, or when output-only transitions exceed ${(QUALITY_RULES.maxCellTransitionSpuriousRatio * 100).toFixed(0)}% of output transition strength.`,
    `- Axis cell transitions: review when either horizontal or vertical cell-adjacency transitions breach the same cell transition limits.`,
    `- Diagonal cell transitions: review when at least ${QUALITY_RULES.minCellDiagonalTransitionCount} source diagonal cell-adjacency transitions retain less than ${(QUALITY_RULES.minCellDiagonalTransitionRetention * 100).toFixed(0)}% of their strength, or when output-only diagonal transitions exceed ${(QUALITY_RULES.maxCellDiagonalTransitionSpuriousRatio * 100).toFixed(0)}% of output diagonal transition strength.`,
    `- Directional diagonal cell transitions: review when either diagonal direction breaches the same diagonal transition limits.`,
    `- Source disorder: review when intra-cell source MAE exceeds ${QUALITY_RULES.highCellMae}.`,
    `- Preservation: review when average MAE exceeds ${QUALITY_RULES.maxPreservationMae} or p95 exceeds ${QUALITY_RULES.maxPreservationP95}.`,
    `- Regional preservation: review when any 8x8 canvas tile exceeds MAE ${QUALITY_RULES.maxTilePreservationMae} or tile p95 exceeds ${QUALITY_RULES.maxTilePreservationP95}.`,
    `- Alpha preservation: review when alpha MAE exceeds ${QUALITY_RULES.maxAlphaMae} or p95 exceeds ${QUALITY_RULES.maxAlphaP95}.`,
    `- Regional alpha preservation: review when any 8x8 canvas tile alpha MAE exceeds ${QUALITY_RULES.maxAlphaTileMae} or alpha tile p95 exceeds ${QUALITY_RULES.maxAlphaTileP95}.`,
    `- Alpha silhouette: review when visible alpha coverage falls outside ${QUALITY_RULES.minAlphaCoverageRatio}-${QUALITY_RULES.maxAlphaCoverageRatio}, mask IoU drops below ${QUALITY_RULES.minAlphaMaskIou}, or visible bounds drift more than ${(QUALITY_RULES.maxAlphaBBoxDriftRatio * 100).toFixed(1)}% of the canvas.`,
    `- Alpha components: review when at least ${QUALITY_RULES.minAlphaComponentCount} visible alpha components change count, area, bounds, perimeter, or position between source and output, when at least ${QUALITY_RULES.minAlphaHoleCount} alpha hole changes count, or when at least ${QUALITY_RULES.minAlphaSmallComponentCount} small alpha component changes count.`,
    `- Alpha semitransparency: review when at least ${QUALITY_RULES.minAlphaSemitransparentPixelCount} source semitransparent pixels retain less than ${(QUALITY_RULES.minAlphaSemitransparentRetention * 100).toFixed(0)}%, source semitransparent alpha value MAE exceeds ${QUALITY_RULES.maxAlphaSemitransparentValueMae} or p95 exceeds ${QUALITY_RULES.maxAlphaSemitransparentValueP95}, or at least ${QUALITY_RULES.minAlphaSemitransparentPixelCount} output semitransparent pixels are more than ${(QUALITY_RULES.maxAlphaSemitransparentSpuriousRatio * 100).toFixed(0)}% output-only.`,
    `- Alpha edge map: review when at least ${QUALITY_RULES.minAlphaEdgeCount} source alpha edges retain less than ${(QUALITY_RULES.minAlphaEdgeRecall * 100).toFixed(0)}%, overlap drops below ${QUALITY_RULES.minAlphaEdgeJaccard}, or output-only alpha edges exceed ${(QUALITY_RULES.maxAlphaEdgeSpuriousRatio * 100).toFixed(0)}%.`,
    `- Contrast: review when snapped contrast ratio falls outside ${QUALITY_RULES.minContrastRatio}-${QUALITY_RULES.maxContrastRatio}.`,
    `- Chroma: review when colorful inputs with mean chroma at least ${QUALITY_RULES.minChromaMeanForRatio} fall outside chroma ratio ${QUALITY_RULES.minChromaRatio}-${QUALITY_RULES.maxChromaRatio}.`,
    `- Hue: review when at least ${QUALITY_RULES.minHueSampleCount} colorful pixels have hue error mean > ${QUALITY_RULES.maxHueErrorMean} degrees or p95 > ${QUALITY_RULES.maxHueErrorP95} degrees.`,
    `- Line strength: review when resized snap edge strength falls outside ${QUALITY_RULES.minLineEdgeRatio}-${QUALITY_RULES.maxLineEdgeRatio}x the source edge strength.`,
    `- Edge direction: review when at least ${QUALITY_RULES.minEdgeDirectionCount} strong source and output edges shift x/y/diagonal direction histogram by more than ${QUALITY_RULES.maxEdgeDirectionDrift}.`,
    `- Edge map overlap: review when fewer than ${(QUALITY_RULES.minEdgeRecall * 100).toFixed(0)}% of strong source edges survive nearby, when more than ${(QUALITY_RULES.maxEdgeSpuriousRatio * 100).toFixed(0)}% of strong output edges are not near source edges, or when tolerant edge overlap drops below ${QUALITY_RULES.minEdgeJaccard}.`,
    `- Regional edge map: review when any eligible 4x4 canvas tile keeps less than ${(QUALITY_RULES.minEdgeTileRecall * 100).toFixed(0)}% of strong source edges nearby, or when an eligible output tile has more than ${(QUALITY_RULES.maxEdgeTileSpuriousRatio * 100).toFixed(0)}% output-only strong edges.`,
    '',
  ]
}

export function toMarkdown(summary) {
  const headers = [
    'dataset',
    'file',
    'input',
    'output',
    'outputCoverage',
    'grid',
    'expectedGrid',
    'sourceCellSize',
    'aspectError',
    'edgeAlignment',
    'axisEdgeAlignmentMin',
    'phaseAlignment',
    'axisPhaseAlignmentMin',
    'cellColorDominance',
    'cellColorDominanceP05',
    'exactLowPaletteCellColorEligible',
    'sourceCellColorAdjacencyCount',
    'outputCellColorAdjacencyCount',
    'cellColorAdjacencyDrift',
    'sourceCellColorDiagonalAdjacencyCount',
    'outputCellColorDiagonalAdjacencyCount',
    'cellColorDiagonalAdjacencyDrift',
    'sourceCellColorBoundaryPairCount',
    'outputCellColorBoundaryPairCount',
    'cellColorBoundaryPairDrift',
    'sourceCellColorDiagonalBoundaryPairCount',
    'outputCellColorDiagonalBoundaryPairCount',
    'cellColorDiagonalBoundaryPairDrift',
    'sourceCellColorBoundaryHorizontalRunCount',
    'outputCellColorBoundaryHorizontalRunCount',
    'cellColorBoundaryHorizontalRunDrift',
    'sourceCellColorBoundaryVerticalRunCount',
    'outputCellColorBoundaryVerticalRunCount',
    'cellColorBoundaryVerticalRunDrift',
    'sourceCellColorNeighborMaskCount',
    'outputCellColorNeighborMaskCount',
    'cellColorNeighborMaskDrift',
    'sourceCellColorQuadPatternCount',
    'outputCellColorQuadPatternCount',
    'sourceCellColorDistinctQuadPatternCount',
    'outputCellColorDistinctQuadPatternCount',
    'cellColorQuadPatternDrift',
    'sourceCellColorWindowPatternCount',
    'outputCellColorWindowPatternCount',
    'sourceCellColorDistinctWindowPatternCount',
    'outputCellColorDistinctWindowPatternCount',
    'cellColorWindowPatternDrift',
    'sourceCellColorHorizontalRunCount',
    'outputCellColorHorizontalRunCount',
    'cellColorHorizontalRunDrift',
    'sourceCellColorVerticalRunCount',
    'outputCellColorVerticalRunCount',
    'cellColorVerticalRunDrift',
    'sourceCellColorRowProjectionCount',
    'outputCellColorRowProjectionCount',
    'cellColorRowProjectionDrift',
    'sourceCellColorColumnProjectionCount',
    'outputCellColorColumnProjectionCount',
    'cellColorColumnProjectionDrift',
    'sourceCellColorComponentCount',
    'outputCellColorComponentCount',
    'sourceCellColorComponentHoleCount',
    'outputCellColorComponentHoleCount',
    'cellColorComponentCountDrift',
    'cellColorComponentAreaDrift',
    'cellColorComponentBBoxDrift',
    'cellColorComponentHoleCountDrift',
    'cellColorComponentPerimeterDrift',
    'cellColorComponentPositionDrift',
    'sourceSmallCellColorComponentCount',
    'outputSmallCellColorComponentCount',
    'smallCellColorComponentCountDrift',
    'cellAlphaErrorMean',
    'cellAlphaErrorP95',
    'cellAlphaErrorMax',
    'cellColorErrorMean',
    'cellColorErrorP95',
    'cellColorErrorMax',
    'cellTransitionRetention',
    'cellTransitionSpuriousRatio',
    'cellTransitionErrorMean',
    'cellDiagonalTransitionRetention',
    'cellDiagonalTransitionSpuriousRatio',
    'cellDiagonalTransitionErrorMean',
    'cellDiagonalTransitionDirectionRetentionMin',
    'cellDiagonalTransitionDirectionSpuriousRatioMax',
    'cellDiagonalTransitionDownRightRetention',
    'cellDiagonalTransitionDownLeftRetention',
    'cellDiagonalTransitionDownRightSpuriousRatio',
    'cellDiagonalTransitionDownLeftSpuriousRatio',
    'cellTransitionAxisRetentionMin',
    'cellTransitionAxisSpuriousRatioMax',
    'cellTransitionXRetention',
    'cellTransitionYRetention',
    'cellTransitionXSpuriousRatio',
    'cellTransitionYSpuriousRatio',
    'sourceCellTransitionCount',
    'sourceCellTransitionXCount',
    'sourceCellTransitionYCount',
    'sourceCellDiagonalTransitionCount',
    'sourceCellDiagonalTransitionDownRightCount',
    'sourceCellDiagonalTransitionDownLeftCount',
    'outputCellTransitionCount',
    'outputCellTransitionXCount',
    'outputCellTransitionYCount',
    'outputCellDiagonalTransitionCount',
    'outputCellDiagonalTransitionDownRightCount',
    'outputCellDiagonalTransitionDownLeftCount',
    'cellMae',
    'outputCellMae',
    'outputAlphaCellMae',
    'preservationMae',
    'preservationP95',
    'tilePreservationMaxMae',
    'tilePreservationP95Mae',
    'alphaMae',
    'alphaP95',
    'alphaTileMaxMae',
    'alphaTileP95Mae',
    'alphaCoverageRatio',
    'alphaMaskIou',
    'alphaBBoxDriftPx',
    'alphaBBoxDriftRatio',
    'alphaComponentCount',
    'outputAlphaComponentCount',
    'alphaComponentCountDrift',
    'alphaComponentAreaDrift',
    'alphaComponentBBoxDrift',
    'alphaComponentPerimeterDrift',
    'alphaComponentPositionDrift',
    'alphaHoleCount',
    'outputAlphaHoleCount',
    'alphaHoleCountDrift',
    'alphaSmallComponentCount',
    'outputAlphaSmallComponentCount',
    'alphaSmallComponentCountDrift',
    'alphaSemitransparentPixelCount',
    'outputAlphaSemitransparentPixelCount',
    'alphaSemitransparentRetention',
    'alphaSemitransparentSpuriousRatio',
    'alphaSemitransparentValueMae',
    'alphaSemitransparentValueP95',
    'alphaEdgeCount',
    'outputAlphaEdgeCount',
    'alphaEdgeRecall',
    'alphaEdgeSpuriousRatio',
    'alphaEdgeJaccard',
    'inputChromaMean',
    'outputChromaMean',
    'chromaRatio',
    'lowPaletteCoverageDrift',
    'lowPaletteCoverageRetention',
    'lowPaletteTileCoverageDriftMax',
    'lowPaletteTileCoverageRetentionMin',
    'lowPaletteTileCoverageTileCount',
    'lowPaletteCoverageEligible',
    'hueErrorMean',
    'hueErrorP95',
    'hueSampleCount',
    'contrastRatio',
    'lineEdgeRatio',
    'sourceEdgeDirectionCount',
    'outputEdgeDirectionCount',
    'edgeDirectionDrift',
    'edgeRecall',
    'edgeSpuriousRatio',
    'edgeJaccard',
    'sourceEdgeTileCount',
    'outputEdgeTileCount',
    'edgeTileRecallMin',
    'edgeTileSpuriousMax',
    'repeatGridGap',
    'repeatVisualMae',
    'repeatVisualP95',
    'repeatVisualAlphaMae',
    'repeatVisualAlphaP95',
    'determinismVisualMae',
    'determinismVisualP95',
    'determinismVisualAlphaMae',
    'determinismVisualAlphaP95',
    'expectedGridGap',
    'inputRgbColorCount',
    'inputBucketColorCount',
    'inputColorDominance',
    'outputRgbColorCount',
    'outputPaletteColorCount',
    'outputPaletteUtilization',
    'paletteUtilizationGap',
    'paletteUtilizationTarget',
    'outputColorDominance',
    'paletteDominanceDelta',
    'outputRgbPaletteOverage',
    'lowPaletteRetention',
    'status',
    'issueSummary',
    'objective',
  ]
  const lines = [
    '# Snap Quality Eval',
    '',
    `Color variety: \`${summary.colorVariety}\``,
    '',
    ...criteriaMarkdown(),
    '## Datasets',
    '',
    ...summary.datasets.map((dataset) => `- \`${dataset.name}\`: \`${dataset.dir}\``),
    '',
    '## Aggregate',
    '',
    '```json',
    JSON.stringify(summary.aggregate, null, 2),
    '```',
    '',
    '## Results',
    '',
    '| ' + headers.join(' | ') + ' |',
    '| ' + headers.map(() => '---').join(' | ') + ' |',
  ]

  for (const result of summary.results) {
    lines.push('| ' + headers.map((header) => String(result[header])).join(' | ') + ' |')
  }

  return `${lines.join('\n')}\n`
}
